from enum import Enum

class VendingMachineState(Enum):
    READY = "READY"
    PRODUCT_DISPLAY = "PRODUCT_DISPLAY"
    PRODUCT_DETAILS_READING = "PRODUCT_DETAILS_READING"
    CASH_READING = "CASH_READING"
    CASH_DISPENCING = "CASH_DISPENCING"
    PRODUCT_DISPENCING = "PRODUCT_DISPENCING"

